<img src="https://raw.githubusercontent.com/ils-underground/ils-underground-docs/main/source/img/ils-underground.png">

# ils-underground `all-the-sql` 

## SQL Linting / Style Guide

Using this notebook, and the tool `SQLFluff`, we can lint, and style SQL in a consistant way in the hopes of making it more readable and understandable.

Rules can be configured and can also be ignored. Rules can be found here:
https://docs.sqlfluff.com/en/stable/rules.html

The following rules are ignored:

* `L016` ```Line is too long.```
    
    https://docs.sqlfluff.com/en/stable/rules.html#sqlfluff.core.rules.Rule_L016
* `L022` ```Blank line expected but not found after CTE closing bracket.```
    
    https://docs.sqlfluff.com/en/stable/rules.html#sqlfluff.core.rules.Rule_L022
* `L031` ```Avoid table aliases in from clauses and join conditions.```

    https://docs.sqlfluff.com/en/stable/rules.html#sqlfluff.core.rules.Rule_L031
* `L034` ```Select wildcards then simple targets before calculations and aggregates.```

    https://docs.sqlfluff.com/en/stable/rules.html#sqlfluff.core.rules.Rule_L034
* `L036` ```Select targets should be on a new line unless there is only one select target.```

    https://docs.sqlfluff.com/en/stable/rules.html#sqlfluff.core.rules.Rule_L036
* `L054` ```Inconsistent column references in GROUP BY/ORDER BY clauses.```

    https://docs.sqlfluff.com/en/stable/rules.html#sqlfluff.core.rules.Rule_L054

---

To edit these rules, expand the code below and add them to the config genererated here.

In [1]:
#@title
!pip install -U pip > /dev/null
# there seems to be a bug with the older version ...
!pip install -U regex > /dev/null
!pip install -U sqlfluff > /dev/null

# dems the rules ...
# https://docs.sqlfluff.com/en/stable/rules.html
ils_underground_sql_rules = """\
[sqlfluff]

# verbose is an integer (0-2) indicating the level of log output

verbose = 0

# Turn off color formatting of output

nocolor = False

# Supported dialects https://docs.sqlfluff.com/en/stable/dialects.html

# Or run 'sqlfluff dialects'

dialect = postgres

# One of [raw|jinja|python|placeholder]

templater = jinja

# Comma separated list of rules to check, default to all

rules = all

# Comma separated list of rules to exclude, or None

exclude_rules = L016,L022,L031,L034,L036,L054

# The depth to recursively parse to (0 for unlimited)

recurse = 0

# Below controls SQLFluff output, see max_line_length for SQL output

output_line_length = 80

# Number of passes to run before admitting defeat

runaway_limit = 10

# Ignore errors by category (one or more of the following, separated by commas: lexing,linting,parsing,templating)

ignore = None

# Ignore linting errors found within sections of code coming directly from

# templated code (e.g. from within Jinja curly braces. Note that it does not

# ignore errors from literal code found within template loops.

ignore_templated_areas = True

# can either be autodetect or a valid encoding e.g. utf-8, utf-8-sig

encoding = autodetect

# Ignore inline overrides (e.g. to test if still required)

disable_noqa = False

# Comma separated list of file extensions to lint

# NB: This config will only apply in the root folder

sql_file_exts = .sql,.sql.j2,.dml,.ddl

# Allow fix to run on files, even if they contain parsing errors

# Note altering this is NOT RECOMMENDED as can corrupt SQL

fix_even_unparsable = False


[sqlfluff:indentation]

# See https://docs.sqlfluff.com/en/stable/indentation.html

indented_joins = False

indented_ctes = False

indented_using_on = True

template_blocks_indent = True


[sqlfluff:templater]

unwrap_wrapped_queries = True


[sqlfluff:templater:jinja]

apply_dbt_builtins = True


# Some rules can be configured directly from the config common to other rules

[sqlfluff:rules]

tab_space_size = 4

max_line_length = 80

indent_unit = space

comma_style = trailing

allow_scalar = True

single_table_references = consistent

unquoted_identifiers_policy = all


# Some rules have their own specific config

[sqlfluff:rules:L003]

hanging_indents = True


[sqlfluff:rules:L007]

operator_new_lines = after


[sqlfluff:rules:L010]

# Keywords

capitalisation_policy = consistent

# Comma separated list of words to ignore for this rule

ignore_words = None

ignore_words_regex = None


[sqlfluff:rules:L011]

# Aliasing preference for tables

aliasing = explicit


[sqlfluff:rules:L012]

# Aliasing preference for columns

aliasing = explicit


[sqlfluff:rules:L014]

# Unquoted identifiers

extended_capitalisation_policy = consistent

# Comma separated list of words to ignore for this rule

ignore_words = None

ignore_words_regex = None


[sqlfluff:rules:L016]

# Line length

ignore_comment_lines = False

ignore_comment_clauses = False


[sqlfluff:rules:L026]

# References must be in FROM clause

# Disabled for some dialects (e.g. bigquery)

force_enable = False


[sqlfluff:rules:L028]

# References must be consistently used

# Disabled for some dialects (e.g. bigquery)

force_enable = False


[sqlfluff:rules:L029]

# Keywords should not be used as identifiers.

unquoted_identifiers_policy = aliases

quoted_identifiers_policy = none

# Comma separated list of words to ignore for this rule

ignore_words = None

ignore_words_regex = None


[sqlfluff:rules:L030]

# Function names

extended_capitalisation_policy = consistent

# Comma separated list of words to ignore for this rule

ignore_words = None

ignore_words_regex = None


[sqlfluff:rules:L031]

# Avoid table aliases in from clauses and join conditions.

# Disabled for some dialects (e.g. bigquery)

force_enable = False


[sqlfluff:rules:L038]

# Trailing commas

select_clause_trailing_comma = forbid


[sqlfluff:rules:L040]

# Null & Boolean Literals

capitalisation_policy = consistent

# Comma separated list of words to ignore for this rule

ignore_words = None

ignore_words_regex = None


[sqlfluff:rules:L042]

# By default, allow subqueries in from clauses, but not join clauses

forbid_subquery_in = join


[sqlfluff:rules:L047]

# Consistent syntax to count all rows

prefer_count_1 = False

prefer_count_0 = False


[sqlfluff:rules:L051]

# Fully qualify JOIN clause

fully_qualify_join_types = inner


[sqlfluff:rules:L052]

# Semi-colon formatting approach

multiline_newline = False

require_final_semicolon = False


[sqlfluff:rules:L054]

# GROUP BY/ORDER BY column references

group_by_and_order_by_style = consistent


[sqlfluff:rules:L057]

# Special characters in identifiers

unquoted_identifiers_policy = all

quoted_identifiers_policy = all

allow_space_in_identifier = False

additional_allowed_characters = ""

ignore_words = None

ignore_words_regex = None


[sqlfluff:rules:L059]

# Policy on quoted and unquoted identifiers

prefer_quoted_identifiers = False

ignore_words = None

ignore_words_regex = None

force_enable = False


[sqlfluff:rules:L062]

# Comma separated list of blocked words that should not be used

blocked_words = None


[sqlfluff:rules:L063]

# Data Types

extended_capitalisation_policy = consistent

# Comma separated list of words to ignore for this rule

ignore_words = None

ignore_words_regex = None


[sqlfluff:rules:L064]

# Consistent usage of preferred quotes for quoted literals

preferred_quoted_literal_style = consistent

# Disabled for dialects that do not support single and double quotes for quoted literals (e.g. Postgres)

force_enable = False
"""

with open('.sqlfluff', 'w') as f:
  f.write(ils_underground_sql_rules)

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [2]:
sql = """\
SELECT
id,
record_type_code,
record_num
FROM
sierra_view.record_metadata AS rm
ORDER BY
rm.id
LIMIT 100
"""

with open('test.sql', 'w') as f:
  f.write(sql)

!sqlfluff lint test.sql

== [test.sql] FAIL
L:   2 | P:   1 | L003 | Expected 1 indentations, found 0 [compared to line 01]
L:   2 | P:   1 | L028 | Unqualified reference 'id' found in single table select.
L:   3 | P:   1 | L003 | Expected 1 indentations, found 0 [compared to line 01]
L:   3 | P:   1 | L028 | Unqualified reference 'record_type_code' found in single
                       | table select.
L:   4 | P:   1 | L003 | Expected 1 indentations, found 0 [compared to line 01]
L:   4 | P:   1 | L028 | Unqualified reference 'record_num' found in single table
                       | select.
L:   6 | P:   1 | L003 | Expected 1 indentations, found 0 [compared to line 05]
L:   8 | P:   1 | L003 | Expected 1 indentations, found 0 [compared to line 07]
L:   8 | P:   1 | L028 | Qualified reference 'rm.id' found in single table select
                       | which is inconsistent with previous references.
All Finished 📜 🎉!

In [3]:
# below is a fairly complex bit of SQL that is "properly linted" 
#
sql = """\
-- ###
-- #
-- build a list of item data
-- related to
--   items of type dvd (itype 100, 101)
--   items checked out <= '2021-01-01' OR never
--   title publish_year <= 2019
-- #
-- ###
WITH bib_item_data AS (
    SELECT
        ir.record_id,
        ir.itype_code_num,
        ir.location_code,
        ir.item_status_code,
        ir.last_checkin_gmt,
        ir.last_checkout_gmt,
        ir.checkout_total,
        ir.is_suppressed,
        c.checkout_gmt,
        c.due_gmt,
        brp.bib_record_id,
        brp.material_code,
        brp.best_title,
        brp.best_author,
        brp.publish_year
    FROM sierra_view.item_record AS ir
    LEFT JOIN sierra_view.bib_record_item_record_link AS brirl ON brirl.item_record_id = ir.record_id
    LEFT JOIN sierra_view.bib_record_property AS brp ON brp.bib_record_id = brirl.bib_record_id
    LEFT OUTER JOIN sierra_view.checkout AS c ON c.item_record_id = ir.record_id
    WHERE
        ir.itype_code_num IN(
            -- looking at DVD item types ...
            100, -- new release dvds
            101  -- dvd/videocassette
        )
        AND (ir.last_checkout_gmt <= '2021-01-01' )
        -- OR ir.last_checkout_gmt IS NULL )
        AND brp.publish_year <= 2019
)
SELECT
    ID2RECKEY(bd.bib_record_id) AS bib_record_num,
    bd.material_code,
    bd.best_title,
    bd.best_author,
    bd.publish_year,
    JSON_AGG(DISTINCT bd.location_code ORDER BY bd.location_code ASC) AS item_locations,
    MIN(bd.last_checkout_gmt) AS earliest_item_checkout,
    MAX(bd.last_checkout_gmt) AS latest_item_checkout,
    MAX(bd.checkout_gmt) AS latest_checkout,
    COUNT(*) AS count_total_items,
    COUNT(*) FILTER (WHERE bd.item_status_code NOT IN ('$', 'a', 'm', 'n', 'r', 's', 'v', 'w', 'z')) AS live_items,
    SUM(bd.checkout_total) AS circ,
    SUM(bd.checkout_total) FILTER (WHERE bd.item_status_code NOT IN('$', 'a', 'm', 'n', 'r', 's', 'v', 'w', 'z')) AS live_circ,
    -- NOTE: here are a couple of lines where we've broken the long line up
    SUM(bd.checkout_total)
    / (COUNT(*) * 1.0) AS avg_circ,
    SUM(bd.checkout_total) FILTER (WHERE bd.item_status_code NOT IN('$', 'a', 'm', 'n', 'r', 's', 'v', 'w', 'z'))
    / (COUNT(*) FILTER (WHERE bd.item_status_code NOT IN('$', 'a', 'm', 'n', 'r', 's', 'v', 'w', 'z')) * 1.0) AS avg_live_circ
FROM bib_item_data AS bd
WHERE
    -- here's where we ONLY include titles on the final list where they have ALL items with a MAX last circulation date 
    bd.bib_record_id IN(
        SELECT
            bd2.bib_record_id
        FROM bib_item_data AS bd2
        LEFT JOIN sierra_view.bib_record_item_record_link AS brirl2 ON brirl2.bib_record_id = bd2.bib_record_id
        LEFT JOIN sierra_view.item_record AS ir2 ON ir2.record_id = brirl2.item_record_id
        -- you may want to consider the sierra_view.checkout table here as well
        GROUP BY
            1
        HAVING
            -- again, you could use the COALESCE function to choose between the first non-NULL values of
            -- either checkout.checkout_gmt or ir2.last_checkout_gmt
            MAX(ir2.last_checkout_gmt) <= '2021-01-01'
    )
GROUP BY
    1, 2, 3, 4, 5
"""

with open('test.sql', 'w') as f:
  f.write(sql)

!sqlfluff lint test.sql

All Finished 📜 🎉!

In [4]:
# !sqlfluff parse test.sql